# Generated by Django 3.2 on 2023-09-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanditeForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, max_length=75)),
                ('last_name', models.TextField(blank=True, max_length=75)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default=' ', upload_to='images/')),
                ('partiya', models.TextField(blank=True, max_length=75)),
            ],
            options={
                'verbose_name': 'Форма Кандидата',
                'verbose_name_plural': 'Формы Кандидатов',
            },
        ),
    ]
