# Generated by Django 3.2 on 2023-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=75)),
                ('last_name', models.TextField(blank=True, max_length=75)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default=' ', upload_to='images/')),
                ('partiya', models.TextField(blank=True, max_length=75)),
            ],
        ),
    ]
