# Generated by Django 3.2 on 2023-09-24 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateform',
            options={'verbose_name': 'Форма Кандидата', 'verbose_name_plural': 'Формы Кандидатов'},
        ),
        migrations.AddField(
            model_name='candidateform',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
