# Generated by Django 3.2 on 2023-09-24 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_customuser_candidaterm'),
        ('golosApp', '0002_auto_20230924_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateForm',
            new_name='CanditeForm',
        ),
    ]
