# Generated by Django 3.2 on 2023-09-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golosApp', '0002_auto_20230924_1434'),
        ('users', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='candidaterm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golosApp.candidateform'),
        ),
    ]
